{application,host,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{host_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[db_host,host,host_app,host_sup,lib_db,lib_db_host,
                        lib_host]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
